---
# File: install_service.yml

- name: Install and Start Service
  hosts: localhost
  become: true

  vars:
    service_name: httpd
    package_name: httpd

  tasks:
    - name: Install the service
      package:
        name: "{{ package_name }}"
        state: present
      register: install_status

    - name: Start the service
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes
      register: service_status

    - name: Display installation status
      debug:
        msg: "Service installation completed successfully"
      when: install_status is succeeded

    - name: Display service status
      debug:
        msg: "Service started successfully"
      when: service_status is succeeded
